AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bingsuVoucher

  Sample SAM Template for bingsuVoucher

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AddVoucherFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuVoucher/
      Handler: app.lambda_handler
      Runtime: python3.8

            
  VoucherTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: voucherId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: voucherId
          KeyType: HASH
      TableName: "BingsuVoucher"

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AddVoucherFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AddVoucherFunctionRole.Arn
