AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bingsuVoucher

  Sample SAM Template for bingsuVoucher

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Runtime: python3.8
    Environment:
      Variables:
        BINGSU_VOUCHER_TABLE_NAME: !Ref VoucherTable

Resources:
  AddVoucherFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuVoucher/
      Handler: app.add_voucher
      
  GetVoucherByIdFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuVoucher/
      Handler: app.get_voucher_by_id
      
  GetAvailableVouchersFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bingsuVoucher/
      Handler: app.get_voucher_by_id

            
  VoucherTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: voucher_id
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: voucher_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: status
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection: 
            ProjectionType: ALL
      TableName: "BingsuVoucher"

Outputs:
  AddVoucherFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt AddVoucherFunction.Arn
  AddVoucherFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt AddVoucherFunctionRole.Arn
